miechuliv_image_forum:
    resource: "@MiechulivImageForumBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
    
login:
    pattern:   /login
    defaults: { _controller: "MiechulivImageForumBundle:User:login" }
    
login_check:
    pattern:   /login_check
    
logout:
    path:     /logout

