Miechuliv\ImageForumBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
        
        author:
            - NotBlank: ~
           
            
   
Miechuliv\ImageForumBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
        email:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~